name: Linux Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [
          { CXX: g++-11, C: gcc-11 },
          { CXX: clang++-17, C: clang-17 },
        ]

    steps:
      - name: Install compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.compiler.C }} ${{ matrix.compiler.CXX }}

      - uses: actions/checkout@v4

      - name: Configure CMake for ${{ matrix.build_type }}
        env:
          CC: ${{ matrix.compiler.C }}
          CXX: ${{ matrix.compiler.CXX }}
        run: |
          cmake \
            -S "${{ github.workspace }}" \
            -B "${{ github.workspace }}/build_${{ matrix.build_type }}" \
            -DDSA_ENABLE_TESTING=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build ${{ matrix.build_type }}
        run: |
          cmake \
            --build "${{ github.workspace }}/build_${{ matrix.build_type }}" \
            --config "${{ matrix.build_type }}" \
            --parallel $(nproc)

      - name: Run tests
        working-directory: ${{ github.workspace }}/build_${{ matrix.build_type }}
        run: ctest --output-on-failure
