name: Linux Build

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        build_shared_libs: ["OFF"]
        compiler: [
          { CXX: g++-11, C: gcc-11 },
          { CXX: g++-12, C: gcc-12 },
          { CXX: g++-13, C: gcc-13 },
          { CXX: g++-14, C: gcc-14 },
          { CXX: clang++-17, C: clang-17 },
          { CXX: clang++-18, C: clang-18 },
          { CXX: clang++-19, C: clang-19 },
        ]
    env:
      BUILD_DIR: ${{ github.workspace }}/build_${{ matrix.build_type }}

    steps:
      - name: Install compilers
        run: |
          echo "::group::Install compilers"
          set -e
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.compiler.C }} ${{ matrix.compiler.CXX }}
          echo "::endgroup::"

      - name: Print compiler version
        run: |
          ${{ matrix.compiler.C }} --version
          ${{ matrix.compiler.CXX }} --version

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.3'

      - uses: actions/checkout@v4

      - name: Configure CMake for ${{ matrix.build_type }}
        env:
          CC: ${{ matrix.compiler.C }}
          CXX: ${{ matrix.compiler.CXX }}
        run: |
          cmake \
            -S "${{ github.workspace }}" \
            -B "$BUILD_DIR" \
            -DBUILD_SHARED_LIBS="${{ matrix.build_shared_libs }}" \
            -DDSA_ENABLE_TESTING=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build ${{ matrix.build_type }}
        run: |
          cmake \
            --build "$BUILD_DIR" \
            --config "${{ matrix.build_type }}" \
            --parallel $(nproc)

      - name: Run tests
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          ctest \
            --build-config "${{ matrix.build_type }}" \
            --output-on-failure

      - name: Archive test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.compiler.CXX }}-${{ matrix.build_type }}
          path: ${{ env.BUILD_DIR }}/Testing/Temporary
