name: Linux Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake for ${{ matrix.build_type }}
        run: |
          cmake \
            -S ${{ github.workspace }} \
            -B ${{ github.workspace }}/build_${{ matrix.build_type }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build ${{ matrix.build_type }}
        run: |
          cmake \
            --build ${{ github.workspace }}/build_${{ matrix.build_type }} \
            --config ${{ matrix.build_type }} \
            --parallel $(nproc)
