name: MacOS Build

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15]
        build_type: [Debug, Release]
        build_shared_libs: ["OFF"]
    runs-on: ${{ matrix.os }}
    env:
      BUILD_DIR: ${{ github.workspace }}/build_${{ matrix.build_type }}

    steps:
      - name: Print system info
        run: |
          sw_vers
          date
          sysctl -n hw.logicalcpu

      - name: Print compiler version
        run: |
          clang --version || gcc --version

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.3'

      - uses: actions/checkout@v4

      - name: Configure CMake for ${{ matrix.build_type }}
        run: |
          cmake \
            -GXcode \
            -S "${{ github.workspace }}" \
            -B "$BUILD_DIR" \
            -DBUILD_SHARED_LIBS="${{ matrix.build_shared_libs }}" \
            -DDSA_ENABLE_TESTING=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build ${{ matrix.build_type }}
        run: |
          threads=$(sysctl -n hw.logicalcpu)
          cmake \
            --build "$BUILD_DIR" \
            --config "${{ matrix.build_type }}" \
            --parallel "$threads"

      - name: Run tests
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          ctest \
            --build-config "${{ matrix.build_type }}" \
            --output-on-failure

      - name: Archive test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.os }}-${{ matrix.build_type }}-${{ github.ref_name }}
          path: ${{ env.BUILD_DIR }}/Testing/Temporary
