name: MacOS Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_DIR: ${{ github.workspace }}/build_${{ matrix.build_type }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake for ${{ matrix.build_type }}
        run: |
          cmake \
            -S "${{ github.workspace }}" \
            -B "$BUILD_DIR" \
            -DDSA_ENABLE_TESTING=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build ${{ matrix.build_type }}
        run: |
          cmake \
            --build "$BUILD_DIR" \
            --config "${{ matrix.build_type }}" \
            --parallel $(nproc)

      - name: Run tests
        working-directory: $BUILD_DIR
        run: ctest --output-on-failure
